#url: "https://iiioxoiii.gitlab.io/" # the base hostname & protocol for your site, e.g. http://example.com
#baseurl: "/video-classroom/" # the subpath of your site, e.g. /blog

#url: "https://gitlab.com/iiioxoiii/"
#baseurl: "/video-classroom"

url: ""
baseurl: ""


title: "Video-Classroom" # the name of your site, e.g. ACME Corp.
siteimage: "/images/vuemastery.svg" ## Icona de la esquerra del site
email: "formacioalescola@xtec.cat"
author: "FormacioProfessional"

## Icones que acompanyen els cursos
ico-llicons: "/images/book.svg"
ico-temps: "/images/clock.svg"
ico-grup: "/images/young.svg"

## Cursos
collections:
  lessons:
    output: true
    permalink: /curs/:name/