#url: "https://iiioxoiii.gitlab.io/" # the base hostname & protocol for your site, e.g. http://example.com
#baseurl: "/video-classroom/" # the subpath of your site, e.g. /blog

#url: "https://gitlab.com/iiioxoiii/"
#baseurl: "/video-classroom"

url: "https://github.com/iiioxoiii/"
#url: ""
baseurl: "video-classroom-fp"


title: "Video-Classroom-fp" # the name of your site, e.g. ACME Corp.

siteimage: "/images/vuemastery.svg" ## Icona de la esquerra del site

email: "formacioalescola@xtec.cat"
author: "FormacioProfessional"

## Cursos
collections:
  lessons:
    output: true
    permalink: /:name/